default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: klaxon_development
  username: <%= `whoami` %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: klaxon_test
  username: <%= `whoami` %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: klaxon_production
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
